# Generated by Django 5.2.1 on 2025-05-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='smax_capacity',
            new_name='max_capacity',
        ),
    ]
