# Generated by Django 5.2.1 on 2025-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
