# Generated by Django 5.2.1 on 2025-06-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Canteen Admin'), (3, 'Super User')], default=3),
        ),
    ]
